name: Test Manual Workflow

on:
    workflow_dispatch:
        inputs:
            Environment:
                description: 'Test Environnement '
                required: true
                default: '/dev'

jobs:
    manual-job:
        runs-on: ubuntu-latest
        environment: env
        steps:   
        - name: Exemple
          run: |
            echo "Mon exemple"
            echo "Env Name: ${{ github.event.inputs.Environment }}"
        - name: GitHub Variable
          run : echo '${{ toJson(github)}}'
        - name: Runner Variable
          run: echo '${{ toJson(runner)}}'
        - name: Secrets Variable
          run: echo '${{ toJson(secrets)}}'
        - name: Environment Variable
          run: echo '${{env.MY_API_URL}}'